:asset_root: public
:load_path:
  - app/javascripts
  - vendor/sprockets/*/src
  - vendor/plugins/*/javascripts
  - vendor/plugins/*/app/javascripts
:source_files:
  - app/javascripts/jquery/jquery.min.js
  - app/javascripts/jquery/jquery-ui.min.js
  - app/javascripts/*.js
  - app/javascripts/application.js
